// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/reporter/reporter.go

// Package reporter is a generated GoMock package.
package reporter

import (
	reflect "reflect"

	models "github.com/DataDog/datadog-sbom-generator/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// Errorf mocks base method.
func (m *MockReporter) Errorf(format string, a ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockReporterMockRecorder) Errorf(format interface{}, a ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, a...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockReporter)(nil).Errorf), varargs...)
}

// HasErrored mocks base method.
func (m *MockReporter) HasErrored() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasErrored")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasErrored indicates an expected call of HasErrored.
func (mr *MockReporterMockRecorder) HasErrored() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasErrored", reflect.TypeOf((*MockReporter)(nil).HasErrored))
}

// Infof mocks base method.
func (m *MockReporter) Infof(format string, a ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockReporterMockRecorder) Infof(format interface{}, a ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, a...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockReporter)(nil).Infof), varargs...)
}

// PrintResult mocks base method.
func (m *MockReporter) PrintResult(vulnResult *models.VulnerabilityResults) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrintResult", vulnResult)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrintResult indicates an expected call of PrintResult.
func (mr *MockReporterMockRecorder) PrintResult(vulnResult interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintResult", reflect.TypeOf((*MockReporter)(nil).PrintResult), vulnResult)
}

// Verbosef mocks base method.
func (m *MockReporter) Verbosef(format string, a ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	m.ctrl.Call(m, "Verbosef", varargs...)
}

// Verbosef indicates an expected call of Verbosef.
func (mr *MockReporterMockRecorder) Verbosef(format interface{}, a ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, a...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verbosef", reflect.TypeOf((*MockReporter)(nil).Verbosef), varargs...)
}

// Warnf mocks base method.
func (m *MockReporter) Warnf(format string, a ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockReporterMockRecorder) Warnf(format interface{}, a ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, a...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockReporter)(nil).Warnf), varargs...)
}
