<Project>

  <ItemGroup>
    <!-- Central package management versions -->
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.App" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <GlobalVersion>2.1.28</GlobalVersion>
  </PropertyGroup>

</Project>
