[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "my-app"
version = "1.0.0"

[tool.poetry.dependencies]
python = "^3.11"
requests = "==2.33.1"

[tool.poetry.dev-dependencies]
black = "==23.1.0"

[tool.poetry.group.test.dependencies]
pytest = "==7.4.4"
pytest-cov = {version = "==4.1.0"}
