name: test
description: "Runs go tests"
inputs:
  upload_coverage:
    description: Whether or not to upload the coverage file
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Run go test
      id: test
      shell: bash
      env:
        TEST_ACCEPTANCE: true
      run: ./scripts/run_tests.sh
    - name: Rename coverage file
      shell: bash
      run: mv coverage.out "${{matrix.os}}.cov"
    - name: Upload coverage
      # We are uploading coverage because it already exceed GH action output size limit
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
      if: ${{inputs.upload_coverage == 'true'}}
      with:
        name: ${{matrix.os}}.cov
        path: ${{matrix.os}}.cov
        retention-days: 1
        if-no-files-found: error
