package models

// Standard lockfile names used by extractors
const (
// APKInstalled              = "/lib/apk/db/installed"
// BuildscriptGradleLockfile = "buildscript-gradle.lockfile"
// CargoLock                 = "Cargo.lock"
// ComposerLock              = "composer.lock"
// ConanLock                 = "conan.lock"
//CSProj                    = ".csproj"
//DpkgStatus                = "/var/lib/dpkg/status"
//GemfileLock               = "Gemfile.lock"
//GoBinary                  = "go-binary"
//GoLock                    = "go.sum"
//GoMod                     = "go.mod"
//GradleLockfile            = "gradle.lockfile"
//GradleVerificationMetadata = "gradle-verification-metadata.xml"
//GradleVerificationXML     = "gradle/verification-metadata.xml"
//MavenLock                 = "maven-lock"
//MixLock                   = "mix.lock"
//NodeModules               = "node_modules"
//NugetCsProjFile           = "csproj"
//NugetLock                 = "packages.lock.json"
//PackageLockJSON           = "package-lock.json"
//PackagesLockJSON          = "packages.lock.json"
//PdmLock                   = "pdm.lock"
//PipenvLock                = "Pipfile.lock"
//PipfileLock               = "Pipfile.lock"
//PnpmLockYAML              = "pnpm-lock.yaml"
//PoetryLock                = "poetry.lock"
//PomXML                    = "pom.xml"
//PubspecLock               = "pubspec.lock"
//RenvLock                  = "renv.lock"
//RequirementsTxt           = "requirements.txt"
//RequirementsTXT           = "requirements.txt"
//UvLock                    = "uv.lock"
//YarnLock                  = "yarn.lock"

// BuildscriptGradleLockfile = "buildscript-gradle.lockfile"
// CargoLock                 = "Cargo.lock"
// ComposerLock              = "composer.lock"
// ConanLock                 = "conan.lock"
// GemfileLock               = "Gemfile.lock"
// GoMod                     = "go.mod"
// GradleLockfile            = "gradle.lockfile"
// GradleVerificationXML     = "gradle/verification-metadata.xml"
// MixLock                   = "mix.lock"
// NugetCsProjFile           = "csproj"
// PackageLockJSON           = "package-lock.json"
// PackagesLockJSON          = "packages.lock.json"
// PdmLock                   = "pdm.lock"
// PipfileLock               = "Pipfile.lock"
// PnpmLockYAML              = "pnpm-lock.yaml"
// PoetryLock                = "poetry.lock"
// PomXML                    = "pom.xml"
// PubspecLock               = "pubspec.lock"
// RenvLock                  = "renv.lock"
// RequirementsTXT           = "requirements.txt"
// UvLock                    = "uv.lock"
// YarnLock = "yarn.lock"
)

type ParsedFilePath string

// String returns the string representation of the ParsedFilePath
func (p ParsedFilePath) String() string {
	return string(p)
}

const (
	ApkFilePath                ParsedFilePath = "/lib/apk/db/installed"
	BundlerFilePath            ParsedFilePath = "Gemfile.lock"
	ComposerFilePath           ParsedFilePath = "composer.lock"
	ConanFilePath              ParsedFilePath = "conan.lock"
	CratesFilePath             ParsedFilePath = "Cargo.lock"
	DpkgFilePath               ParsedFilePath = "/var/lib/dpkg/status"
	GolangFilePath             ParsedFilePath = "go.mod"
	GolangBinaryFilePath       ParsedFilePath = "go-binary"
	GradleBuildScriptFilePath  ParsedFilePath = "buildscript-gradle.lockfile"
	GradleVerificationFilePath ParsedFilePath = "gradle/verification-metadata.xml"
	GradleFilePath             ParsedFilePath = "gradle.lockfile"
	HexFilePath                ParsedFilePath = "mix.lock"
	MavenFilePath              ParsedFilePath = "pom.xml"
	NodeModulesPath            ParsedFilePath = "node_modules"
	NpmFilePath                ParsedFilePath = "package-lock.json"
	NuGetCsProjFilePath        ParsedFilePath = "csproj"
	NugetLockFilePath          ParsedFilePath = "packages.lock.json"
	PdmFilePath                ParsedFilePath = "pdm.lock"
	PipfileFilePath            ParsedFilePath = "Pipfile.lock"
	PnpmFilePath               ParsedFilePath = "pnpm-lock.yaml"
	PoetryFilePath             ParsedFilePath = "poetry.lock"
	PubFilePath                ParsedFilePath = "pubspec.lock"
	RenvFilePath               ParsedFilePath = "renv.lock"
	RequirementsFilePath       ParsedFilePath = "requirements.txt"
	UvFilePath                 ParsedFilePath = "uv.lock"
	YarnFilePath               ParsedFilePath = "yarn.lock"
)
