name: Check if License-3rdparty is up to date on PR

on: [pull_request]
permissions:
  contents: read

jobs:
  license-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: .go-version
          check-latest: true
      - name: Installing modvendor tool
        run: go install github.com/goware/modvendor@latest
      - name: Installing wwhrd tool
        run: go install github.com/frapposelli/wwhrd@latest
      - name: Installing go-license-detector tool
        run: GO111MODULE=on go install github.com/go-enry/go-license-detector/v4/cmd/license-detector@latest
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.9.12"
          cache: "pip"
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Run license lint task
        run: inv -e lint-licenses
